services:
  app:
    image: one-lamp-app
    ports:
      - "80:80"
    environment:
      - ENV=prod
      - POETRY_VERSION=1.6.1
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PORT=80
      - WORKERS=4
      - PYTHONUNBUFFERED=1
    env_file:
      - .env
  redis:
    image: "redis:7.2.1-alpine"
    ports:
      - "6379:6379"