services:
  app:
    build:
      context: .
      args:
        - ENV=prod
        - POETRY_VERSION=1.6.1
    ports:
      - "80:80"
    environment:
      - ENV=prod
      - POETRY_VERSION=1.6.1
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PORT=80
      - WORKERS=4
  redis:
    image: "redis:7.2.1-alpine"
    ports:
      - "6379:6379"